config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', include('pages.urls'))
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index')
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'), # users/login/,
    path('login/<int:id>/', views.login_detail, name='login-detail'),
    path('login/index', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name = 'signup'),
]

pybo/models.py
from django.db import models


class User(models.Model) :
    username = models.CharField(max_length=50, unique= True)
    password = models.CharField(max_length=50)

pages/views.py
from django.shortcuts import render

def index(request):

    context = {
        "is_login" : False,
        "username": None,
        "password" : None
    }

    is_login = request.COOKIES.get('is_login', False)
    if is_login :
        context['is_login'] = True
        context['username'] = request.COOKIES['username']
        context['password'] = request.COOKIES['password']

    return render(request,'index.html', context)

pybo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError

from pybo.models import User

def login(request):
    context = {
        'method': request.method,
        'is_valid': True
    }

    if (request.method =='GET') :
        return render(request, 'pybo/login.html', context)

    if (request.method=='POST'):
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username, password=password)
            response = redirect('pages:index')
            response.set_cookie('is_login', True)
            response.set_cookie('username', user.username)
            response.set_cookie('password', user.password)

            return response

        except User.DoesNotExist: #db에 값이 없어 로그인 할 수 없는 경우
            context['is_valid'] = False
        return render(request, 'pybo/login.html', context)

def login_detail(request, id):
    return HttpResponse('user id 는' + str(id) + '입니다.')

def index(request) :
    return render(request,'index.html')

def logout(request):
    response = redirect('pages:index')
    response.delete_cookie('is_login')
    response.delete_cookie('username')
    response.delete_cookie('password')

    return response

def signup(request):
    context = {
        'blank' : False
    }
    template_name = "pybo/signup.html"

    if request.method =="GET":
        return render(request, template_name, context)

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        if username =='' or password == '':
            context['blank'] = True
            return render(request, template_name, context)
        exist =User.objects.filter(username=username).exists()
        if exist:
            context['exist'] = exist
            return render(request, template_name, context)

        User.objects.create(username=username, password=password)

        return redirect('users:login')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello world!!</h1>
    {% if is_login %}
    <p>유저 아이디는 {{ username }} 이고</p>
    <p>비밀번호는 {{ password }} 입니다.</p>
    <a href="{% url 'users:logout' %}">로그아웃</a>
    {% else %}
    <a href="{% url 'users:login' %}">로그인 하러가기</a>
    <a href="{% url 'users:signup'  %}">회원가입 하기</a>
    {% endif %}


</body>
</html>

templates/pybo/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content ="IE=edge">
    <meta name ="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인 페이지</title>
</head>

<body>
{% if method == 'GET' %}
  <form method="POST"> {% csrf_token %}
      <label for="username">아이디</label>
      <input type ="text" name ="username" id="username">
      <label for="password">비밀번호</label>
      <input type="password" name="password" id="password">
      <input type="submit">
  </form>
{% else %}
    {% if not is_valid %}
        <h1 style="color: red">로그인에 실패했습니다.</h1>
    {% else %}
        <h1 style="color: blue">로그인에 성공</h1>
    {% endif %}
{% endif %}
</body>
</html>

templates/pybo/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>회원가입 페이지</title>
</head>

<body>
  <header>회원가입 페이지</header>
  <form method="POST">{% csrf_token %}
    <label for="username">아이디</label>
    <input type="text" name="username" id="username">
    <label for="password">비밀번호</label>
    <input type="password" name="password" id="password">
    <input type="submit">
  </form>
  {% if blank %}
  <span style="color: red">유저 아이디 혹은 비밀번호를 입력해주세요</span>
  {% endif %}
  {% if exist %}
  <span style="color: red">유저 아이디가 이미 존재합니다</span>
  {% endif %}
</body>

</html>